export const filmai = [
  {
    id: 1,
    title: 'The Rockies',
    genre: 'TV Series',
    rating: 'E',
    year: 2015,
    description: 'A breathtaking journey through the Rocky Mountains.',
    miniature: 'https://m.media-amazon.com/images/I/51PiUn6TyFL._SY445_SX342_.jpg',
    cover: 'https://m.media-amazon.com/images/I/51PiUn6TyFL._SY445_SX342_.jpg',
    favorite: true,
  },
  {
    id: 2,
    title: 'Relentless',
    genre: 'Movie',
    rating: 'PG',
    year: 2017,
    description: 'A story of survival against all odds.',
    miniature: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg',
    cover: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg',
    favorite: false,
  },
  {
    id: 3,
    title: 'Community of Ours',
    genre: 'TV Series',
    rating: '18+',
    year: 2018,
    description: 'A look into the complex lives of a diverse neighborhood.',
    miniature:
      'https://cdn.prod.website-files.com/5de2db6d3719a1e2f3e4454c/64da5dbc0e0547eb29e20941_48dd9b8a-8fb0-4dc1-9d9a-4850bf5e93c6.webp',
    cover:
      'https://cdn.prod.website-files.com/5de2db6d3719a1e2f3e4454c/64da5dbc0e0547eb29e20941_48dd9b8a-8fb0-4dc1-9d9a-4850bf5e93c6.webp',
    favorite: false,
  },
  {
    id: 4,
    title: 'Van Life',
    genre: 'Movie',
    rating: 'PG',
    year: 2015,
    description: 'An adventurous road trip exploring remote destinations.',
    miniature: 'https://upload.wikimedia.org/wikipedia/en/7/78/Sandmankieth.png',
    cover: 'https://upload.wikimedia.org/wikipedia/en/7/78/Sandmankieth.png',
    favorite: false,
  },
  {
    id: 5,
    title: 'The Heiress',
    genre: 'Movie',
    rating: 'PG',
    year: 2021,
    description: 'The dramatic tale of a young woman navigating family legacy.',
    miniature:
      'https://grantscomics.com/cdn/shop/products/143777116_276717237133880_2090893313337939907_n_1024x1024@2x.jpg?v=1611777470',
    cover:
      'https://grantscomics.com/cdn/shop/products/143777116_276717237133880_2090893313337939907_n_1024x1024@2x.jpg?v=1611777470',
    favorite: false,
  },
  {
    id: 6,
    title: 'Off the Track',
    genre: 'Movie',
    rating: '18+',
    year: 2017,
    description: 'A high-octane race through a dangerous underworld.',
    miniature:
      'https://render.fineartamerica.com/images/rendered/default/poster/6/8/break/images/artworkimages/medium/3/v-for-vendetta-designer-mind.jpg',
    cover:
      'https://render.fineartamerica.com/images/rendered/default/poster/6/8/break/images/artworkimages/medium/3/v-for-vendetta-designer-mind.jpg',
    favorite: false,
  },
  {
    id: 7,
    title: 'Whispering Hill',
    genre: 'Movie',
    rating: 'E',
    year: 2017,
    description: 'A chilling mystery set in a foggy countryside.',
    miniature:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Infinity_Gauntlet_1.jpg/220px-Infinity_Gauntlet_1.jpg',
    cover: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Infinity_Gauntlet_1.jpg/220px-Infinity_Gauntlet_1.jpg',
    favorite: false,
  },
  {
    id: 8,
    title: '112',
    genre: 'TV Series',
    rating: 'PG',
    year: 2013,
    description: 'A gripping medical drama following emergency responders.',
    miniature: 'https://d2lzb5v10mb0lj.cloudfront.net/covers/300/30/3004627.jpg',
    cover: 'https://d2lzb5v10mb0lj.cloudfront.net/covers/300/30/3004627.jpg',
    favorite: false,
  },
  {
    id: 9,
    title: 'Beyond the Horizon',
    genre: 'Movie',
    rating: 'PG-13',
    year: 2019,
    description: "A sci-fi adventure about humanity's reach for the stars.",
    miniature: 'https://parigibooks.cdn.bibliopolis.com/pictures/28863.jpg?auto=webp&v=1492910236',
    cover: 'https://parigibooks.cdn.bibliopolis.com/pictures/28863.jpg?auto=webp&v=1492910236',
    favorite: false,
  },
  {
    id: 10,
    title: 'Hidden Truths',
    genre: 'TV Series',
    rating: '18+',
    year: 2020,
    description: 'A crime thriller uncovering secrets in a small town.',
    miniature: 'https://example.com/miniature10.jpg',
    cover: 'https://example.com/cover10.jpg',
    favorite: false,
  },
  {
    id: 11,
    title: 'The Rockies',
    genre: 'TV Series',
    rating: 'E',
    year: 2015,
    description: 'A breathtaking journey through the Rocky Mountains.',
    miniature: 'https://m.media-amazon.com/images/I/51PiUn6TyFL._SY445_SX342_.jpg',
    cover: 'https://m.media-amazon.com/images/I/51PiUn6TyFL._SY445_SX342_.jpg',
    favorite: false,
  },
  {
    id: 12,
    title: 'Relentless',
    genre: 'Movie',
    rating: 'PG',
    year: 2017,
    description: 'A story of survival against all odds.',
    miniature: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg',
    cover: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg',
    favorite: false,
  },
  {
    id: 13,
    title: 'Community of Ours',
    genre: 'TV Series',
    rating: '18+',
    year: 2018,
    description: 'A look into the complex lives of a diverse neighborhood.',
    miniature:
      'https://cdn.prod.website-files.com/5de2db6d3719a1e2f3e4454c/64da5dbc0e0547eb29e20941_48dd9b8a-8fb0-4dc1-9d9a-4850bf5e93c6.webp',
    cover:
      'https://cdn.prod.website-files.com/5de2db6d3719a1e2f3e4454c/64da5dbc0e0547eb29e20941_48dd9b8a-8fb0-4dc1-9d9a-4850bf5e93c6.webp',
    favorite: false,
  },
  {
    id: 14,
    title: 'Van Life',
    genre: 'Movie',
    rating: 'PG',
    year: 2015,
    description: 'An adventurous road trip exploring remote destinations.',
    miniature: 'https://upload.wikimedia.org/wikipedia/en/7/78/Sandmankieth.png',
    cover: 'https://upload.wikimedia.org/wikipedia/en/7/78/Sandmankieth.png',
    favorite: false,
  },
  {
    id: 15,
    title: 'The Heiress',
    genre: 'Movie',
    rating: 'PG',
    year: 2021,
    description: 'The dramatic tale of a young woman navigating family legacy.',
    miniature:
      'https://grantscomics.com/cdn/shop/products/143777116_276717237133880_2090893313337939907_n_1024x1024@2x.jpg?v=1611777470',
    cover:
      'https://grantscomics.com/cdn/shop/products/143777116_276717237133880_2090893313337939907_n_1024x1024@2x.jpg?v=1611777470',
    favorite: false,
  },
  {
    id: 16,
    title: 'Off the Track',
    genre: 'Movie',
    rating: '18+',
    year: 2017,
    description: 'A high-octane race through a dangerous underworld.',
    miniature:
      'https://render.fineartamerica.com/images/rendered/default/poster/6/8/break/images/artworkimages/medium/3/v-for-vendetta-designer-mind.jpg',
    cover:
      'https://render.fineartamerica.com/images/rendered/default/poster/6/8/break/images/artworkimages/medium/3/v-for-vendetta-designer-mind.jpg',
    favorite: false,
  },
  {
    id: 17,
    title: 'Whispering Hill',
    genre: 'Movie',
    rating: 'E',
    year: 2017,
    description: 'A chilling mystery set in a foggy countryside.',
    miniature:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Infinity_Gauntlet_1.jpg/220px-Infinity_Gauntlet_1.jpg',
    cover: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Infinity_Gauntlet_1.jpg/220px-Infinity_Gauntlet_1.jpg',
    favorite: false,
  },
  {
    id: 18,
    title: '112',
    genre: 'TV Series',
    rating: 'PG',
    year: 2013,
    description: 'A gripping medical drama following emergency responders.',
    miniature: 'https://d2lzb5v10mb0lj.cloudfront.net/covers/300/30/3004627.jpg',
    cover: 'https://d2lzb5v10mb0lj.cloudfront.net/covers/300/30/3004627.jpg',
    favorite: false,
  },
  {
    id: 19,
    title: 'Beyond the Horizon',
    genre: 'Movie',
    rating: 'PG-13',
    year: 2019,
    description: "A sci-fi adventure about humanity's reach for the stars.",
    miniature: 'https://parigibooks.cdn.bibliopolis.com/pictures/28863.jpg?auto=webp&v=1492910236',
    cover: 'https://parigibooks.cdn.bibliopolis.com/pictures/28863.jpg?auto=webp&v=1492910236',
    favorite: false,
  },
  {
    id: 20,
    title: 'Hidden Truths',
    genre: 'TV Series',
    rating: '18+',
    year: 2020,
    description: 'A crime thriller uncovering secrets in a small town.',
    miniature: 'https://example.com/miniature10.jpg',
    cover: 'https://example.com/cover10.jpg',
    favorite: false,
  },
  {
    id: 21,
    title: 'The Rockies',
    genre: 'TV Series',
    rating: 'E',
    year: 2015,
    description: 'A breathtaking journey through the Rocky Mountains.',
    miniature: 'https://m.media-amazon.com/images/I/51PiUn6TyFL._SY445_SX342_.jpg',
    cover: 'https://m.media-amazon.com/images/I/51PiUn6TyFL._SY445_SX342_.jpg',
    favorite: false,
  },
  {
    id: 22,
    title: 'Relentless',
    genre: 'Movie',
    rating: 'PG',
    year: 2017,
    description: 'A story of survival against all odds.',
    miniature: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg',
    cover: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg',
    favorite: false,
  },
  {
    id: 23,
    title: 'Community of Ours',
    genre: 'TV Series',
    rating: '18+',
    year: 2018,
    description: 'A look into the complex lives of a diverse neighborhood.',
    miniature:
      'https://cdn.prod.website-files.com/5de2db6d3719a1e2f3e4454c/64da5dbc0e0547eb29e20941_48dd9b8a-8fb0-4dc1-9d9a-4850bf5e93c6.webp',
    cover:
      'https://cdn.prod.website-files.com/5de2db6d3719a1e2f3e4454c/64da5dbc0e0547eb29e20941_48dd9b8a-8fb0-4dc1-9d9a-4850bf5e93c6.webp',
    favorite: false,
  },
  {
    id: 24,
    title: 'Van Life',
    genre: 'Movie',
    rating: 'PG',
    year: 2015,
    description: 'An adventurous road trip exploring remote destinations.',
    miniature: 'https://upload.wikimedia.org/wikipedia/en/7/78/Sandmankieth.png',
    cover: 'https://upload.wikimedia.org/wikipedia/en/7/78/Sandmankieth.png',
    favorite: false,
  },
  {
    id: 25,
    title: 'The Heiress',
    genre: 'Movie',
    rating: 'PG',
    year: 2021,
    description: 'The dramatic tale of a young woman navigating family legacy.',
    miniature:
      'https://grantscomics.com/cdn/shop/products/143777116_276717237133880_2090893313337939907_n_1024x1024@2x.jpg?v=1611777470',
    cover:
      'https://grantscomics.com/cdn/shop/products/143777116_276717237133880_2090893313337939907_n_1024x1024@2x.jpg?v=1611777470',
    favorite: false,
  },
  {
    id: 26,
    title: 'Off the Track',
    genre: 'Movie',
    rating: '18+',
    year: 2017,
    description: 'A high-octane race through a dangerous underworld.',
    miniature:
      'https://render.fineartamerica.com/images/rendered/default/poster/6/8/break/images/artworkimages/medium/3/v-for-vendetta-designer-mind.jpg',
    cover:
      'https://render.fineartamerica.com/images/rendered/default/poster/6/8/break/images/artworkimages/medium/3/v-for-vendetta-designer-mind.jpg',
    favorite: false,
  },
  {
    id: 27,
    title: 'Whispering Hill',
    genre: 'Movie',
    rating: 'E',
    year: 2017,
    description: 'A chilling mystery set in a foggy countryside.',
    miniature:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Infinity_Gauntlet_1.jpg/220px-Infinity_Gauntlet_1.jpg',
    cover: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Infinity_Gauntlet_1.jpg/220px-Infinity_Gauntlet_1.jpg',
    favorite: true,
  },
  {
    id: 28,
    title: '112',
    genre: 'TV Series',
    rating: 'PG',
    year: 2013,
    description: 'A gripping medical drama following emergency responders.',
    miniature: 'https://d2lzb5v10mb0lj.cloudfront.net/covers/300/30/3004627.jpg',
    cover: 'https://d2lzb5v10mb0lj.cloudfront.net/covers/300/30/3004627.jpg',
    favorite: false,
  },
  {
    id: 29,
    title: 'Beyond the Horizon',
    genre: 'Movie',
    rating: 'PG-13',
    year: 2019,
    description: "A sci-fi adventure about humanity's reach for the stars.",
    miniature: 'https://parigibooks.cdn.bibliopolis.com/pictures/28863.jpg?auto=webp&v=1492910236',
    cover: 'https://parigibooks.cdn.bibliopolis.com/pictures/28863.jpg?auto=webp&v=1492910236',
    favorite: true,
  },
  {
    id: 30,
    title: 'Hidden Truths',
    genre: 'TV Series',
    rating: '18+',
    year: 2020,
    description: 'A crime thriller uncovering secrets in a small town.',
    miniature: 'https://example.com/miniature10.jpg',
    cover: 'https://example.com/cover10.jpg',
    favorite: false,
  },
  {
    id: 31,
    title: 'The Rockies',
    genre: 'TV Series',
    rating: 'E',
    year: 2015,
    description: 'A breathtaking journey through the Rocky Mountains.',
    miniature: 'https://m.media-amazon.com/images/I/51PiUn6TyFL._SY445_SX342_.jpg',
    cover: 'https://m.media-amazon.com/images/I/51PiUn6TyFL._SY445_SX342_.jpg',
    favorite: false,
  },
  {
    id: 32,
    title: 'Relentless',
    genre: 'Movie',
    rating: 'PG',
    year: 2017,
    description: 'A story of survival against all odds.',
    miniature: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg',
    cover: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg',
    favorite: false,
  },
  {
    id: 33,
    title: 'Community of Ours',
    genre: 'TV Series',
    rating: '18+',
    year: 2018,
    description: 'A look into the complex lives of a diverse neighborhood.',
    miniature:
      'https://cdn.prod.website-files.com/5de2db6d3719a1e2f3e4454c/64da5dbc0e0547eb29e20941_48dd9b8a-8fb0-4dc1-9d9a-4850bf5e93c6.webp',
    cover:
      'https://cdn.prod.website-files.com/5de2db6d3719a1e2f3e4454c/64da5dbc0e0547eb29e20941_48dd9b8a-8fb0-4dc1-9d9a-4850bf5e93c6.webp',
    favorite: true,
  },
  {
    id: 34,
    title: 'Van Life',
    genre: 'Movie',
    rating: 'PG',
    year: 2015,
    description: 'An adventurous road trip exploring remote destinations.',
    miniature: 'https://upload.wikimedia.org/wikipedia/en/7/78/Sandmankieth.png',
    cover: 'https://upload.wikimedia.org/wikipedia/en/7/78/Sandmankieth.png',
    favorite: false,
  },
  {
    id: 35,
    title: 'The Heiress',
    genre: 'Movie',
    rating: 'PG',
    year: 2021,
    description: 'The dramatic tale of a young woman navigating family legacy.',
    miniature:
      'https://grantscomics.com/cdn/shop/products/143777116_276717237133880_2090893313337939907_n_1024x1024@2x.jpg?v=1611777470',
    cover:
      'https://grantscomics.com/cdn/shop/products/143777116_276717237133880_2090893313337939907_n_1024x1024@2x.jpg?v=1611777470',
    favorite: true,
  },
  {
    id: 36,
    title: 'Off the Track',
    genre: 'Movie',
    rating: '18+',
    year: 2017,
    description: 'A high-octane race through a dangerous underworld.',
    miniature:
      'https://render.fineartamerica.com/images/rendered/default/poster/6/8/break/images/artworkimages/medium/3/v-for-vendetta-designer-mind.jpg',
    cover:
      'https://render.fineartamerica.com/images/rendered/default/poster/6/8/break/images/artworkimages/medium/3/v-for-vendetta-designer-mind.jpg',
    favorite: false,
  },
  {
    id: 37,
    title: 'Whispering Hill',
    genre: 'Movie',
    rating: 'E',
    year: 2017,
    description: 'A chilling mystery set in a foggy countryside.',
    miniature:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Infinity_Gauntlet_1.jpg/220px-Infinity_Gauntlet_1.jpg',
    cover: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Infinity_Gauntlet_1.jpg/220px-Infinity_Gauntlet_1.jpg',
    favorite: false,
  },
  {
    id: 38,
    title: '112',
    genre: 'TV Series',
    rating: 'PG',
    year: 2013,
    description: 'A gripping medical drama following emergency responders.',
    miniature: 'https://d2lzb5v10mb0lj.cloudfront.net/covers/300/30/3004627.jpg',
    cover: 'https://d2lzb5v10mb0lj.cloudfront.net/covers/300/30/3004627.jpg',
    favorite: false,
  },
  {
    id: 39,
    title: 'Beyond the Horizon',
    genre: 'Movie',
    rating: 'PG-13',
    year: 2019,
    description: "A sci-fi adventure about humanity's reach for the stars.",
    miniature: 'https://parigibooks.cdn.bibliopolis.com/pictures/28863.jpg?auto=webp&v=1492910236',
    cover: 'https://parigibooks.cdn.bibliopolis.com/pictures/28863.jpg?auto=webp&v=1492910236',
    favorite: false,
  },
  {
    id: 40,
    title: 'Hidden Truths',
    genre: 'TV Series',
    rating: '18+',
    year: 2020,
    description: 'A crime thriller uncovering secrets in a small town.',
    miniature: 'https://example.com/miniature10.jpg',
    cover: 'https://example.com/cover10.jpg',
    favorite: true,
  },
];
